-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: pretty-format-json
    -   id: check-executables-have-shebangs
    -   id: forbid-submodules
    -   id: mixed-line-ending