name: "nix"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  analyze:
    name: update
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - run: nix flake update
    - run: nix flake check
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'chore: update flake.lock'
