name: "nix"

on:
  workflow_dispatch:
  schedule:
    - cron: '32 2 * * *'

jobs:
  analyze:
    name: update
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake update
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'chore: update flake.lock'
